import React, { useEffect, useState } from 'react';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import { FaDownload, FaEnvelope, FaTrash } from 'react-icons/fa';

import { apiGet, apiDelete, apiPost } from '../lib/api';

function formatDate(dateStr: string) {
  const d = new Date(dateStr);
  return d.toLocaleDateString() + ' ' + d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}


export default function PdfHistoryPage() {
  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('All Dates');
  const [pdfs, setPdfs] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  async function fetchPdfs() {
    setLoading(true);
    try {
      const data = await apiGet<any[]>('/pdfs');
      setPdfs(data);
    } catch (e) {
      setPdfs([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchPdfs();
  }, []);

  const filtered = pdfs.filter(pdf =>
    pdf.file.toLowerCase().includes(search.toLowerCase())
    // (dateFilter === 'All Dates' || pdf.date.startsWith(dateFilter))
  );

  const handleDownload = async (file: string) => {
    window.open(`/api/pdfs/${encodeURIComponent(file)}`, '_blank');
  };

  const handleDelete = async (file: string) => {
    if (!window.confirm('Delete this PDF?')) return;
    await apiDelete(`/pdfs/${encodeURIComponent(file)}`);
    fetchPdfs();
  };

  const handleSend = async (file: string) => {
    const to = window.prompt('Email à envoyer :');
    if (!to) return;
    await apiPost(`/pdfs/${encodeURIComponent(file)}/send`, { to });
    alert('PDF envoyé !');
  };

  return (
    <div className="p-6">
      <h2 className="text-2xl font-semibold mb-4">PDF History</h2>
      <div className="flex flex-wrap gap-2 mb-4 items-center">
        <Input
          placeholder="Search PDFs..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          className="w-64"
        />
        <Select value={dateFilter} onChange={e => setDateFilter(e.target.value)}>
          <option>All Dates</option>
          {/* Add more date options dynamically if needed */}
        </Select>
        <Button onClick={fetchPdfs} variant="secondary">Refresh</Button>
      </div>
      <div className="bg-white rounded shadow p-4">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2">PDF FILE</th>
              <th className="text-left py-2">GENERATED BY</th>
              <th className="text-left py-2">DATE</th>
              <th className="text-left py-2">ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((pdf, idx) => (
              <tr key={pdf.file} className="border-b hover:bg-gray-50">
                <td className="py-2">
                  <div className="flex items-center gap-2">
                    <span className="bg-blue-100 text-blue-700 rounded px-2 py-1 font-mono text-xs">PDF</span>
                    <span>{pdf.file}</span>
                  </div>
                  <div className="text-xs text-gray-500">{pdf.size} · PDF</div>
                </td>
                <td className="py-2">{pdf.generatedBy}</td>
                <td className="py-2">{pdf.date ? formatDate(new Date(Number(pdf.date) * 1000).toISOString()) : ''}</td>
                <td className="py-2 flex gap-2">
                  <Button size="sm" variant="primary" title="Download" onClick={() => handleDownload(pdf.file)}><FaDownload /></Button>
                  <Button size="sm" variant="success" title="Send" onClick={() => handleSend(pdf.file)}><FaEnvelope /></Button>
                  <Button size="sm" variant="danger" title="Delete" onClick={() => handleDelete(pdf.file)}><FaTrash /></Button>
                </td>
              </tr>
            ))}
            {filtered.length === 0 && (
              <tr>
                <td colSpan={4} className="text-center text-gray-400 py-8">No PDFs found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
