import React, { useEffect, useState } from 'react';
import { FileText } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { FaDownload, FaEnvelope, FaTrash } from 'react-icons/fa';

import { apiGet, apiDelete, apiPost } from '../lib/api';

function formatDate(dateStr: string) {
  const d = new Date(dateStr);
  return d.toLocaleDateString() + ' ' + d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}


export default function PdfHistoryPage() {
  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('All Dates');
  const [pdfs, setPdfs] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  async function fetchPdfs() {
    setLoading(true);
    try {
      const data = await apiGet<any[]>('/pdfs');
      setPdfs(data);
    } catch (e) {
      setPdfs([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchPdfs();
  }, []);

  const filtered = pdfs.filter(pdf =>
    pdf.file.toLowerCase().includes(search.toLowerCase())
    // (dateFilter === 'All Dates' || pdf.date.startsWith(dateFilter))
  );

  const handleDownload = async (file: string) => {
    window.open(`/api/pdfs/${encodeURIComponent(file)}`, '_blank');
  };

  const handleDelete = async (file: string) => {
    if (!window.confirm('Delete this PDF?')) return;
    await apiDelete(`/pdfs/${encodeURIComponent(file)}`);
    fetchPdfs();
  };

  const handleSend = async (file: string) => {
    const to = window.prompt('Recipient email:');
    if (!to) return;
    await apiPost(`/pdfs/${encodeURIComponent(file)}/send`, { to });
    alert('PDF sent!');
  };

  return (
    <div className="p-6 space-y-6">
      <div className="page-hero">
        <div className="page-hero__topline" aria-hidden />
        <div className="page-hero__layout">
          <div className="min-w-0">
            <div className="page-hero__title-row">
              <div className="page-hero__icon" aria-hidden>
                <FileText className="h-[18px] w-[18px]" />
              </div>

              <div className="min-w-0">
                <div className="mb-2 flex flex-wrap items-center gap-2">
                  <span className="page-hero__badge">PDFs</span>
                </div>

                <h1 className="page-hero__title">
                  <span className="page-hero__title-stack">
                    <span className="page-hero__title-glow" aria-hidden>
                      PDF History
                    </span>
                    <span className="page-hero__title-text">PDF History</span>
                  </span>
                </h1>

                <div className="page-hero__underline" aria-hidden />
                <p className="page-hero__subtitle">Browse, download, and send generated PDFs</p>
              </div>
            </div>
          </div>

          <div className="page-hero__actions">
            <Button onClick={fetchPdfs} variant="secondary" disabled={loading}>
              {loading ? 'Refreshing…' : 'Refresh'}
            </Button>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap gap-2 items-center">
        <Input
          placeholder="Search PDFs..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-64"
        />
        <select
          value={dateFilter}
          onChange={(e) => setDateFilter(e.target.value)}
          className="h-9 rounded-md border border-border bg-background px-3 text-sm text-foreground"
        >
          <option>All Dates</option>
          {/* Add more date options dynamically if needed */}
        </select>
      </div>
      <div className="premium-surface p-4">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2">PDF FILE</th>
              <th className="text-left py-2">GENERATED BY</th>
              <th className="text-left py-2">DATE</th>
              <th className="text-left py-2">ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((pdf, idx) => (
              <tr key={pdf.file} className="border-b hover:bg-gray-50">
                <td className="py-2">
                  <div className="flex items-center gap-2">
                    <span className="bg-blue-100 text-blue-700 rounded px-2 py-1 font-mono text-xs">PDF</span>
                    <span>{pdf.file}</span>
                  </div>
                  <div className="text-xs text-gray-500">{pdf.size} · PDF</div>
                </td>
                <td className="py-2">{pdf.generatedBy}</td>
                <td className="py-2">{pdf.date ? formatDate(new Date(Number(pdf.date) * 1000).toISOString()) : ''}</td>
                <td className="py-2 flex gap-2">
                  <Button size="icon" variant="outline" title="Download" onClick={() => handleDownload(pdf.file)}>
                    <FaDownload />
                  </Button>
                  <Button size="icon" variant="outline" title="Send" onClick={() => handleSend(pdf.file)}>
                    <FaEnvelope />
                  </Button>
                  <Button size="icon" variant="destructive" title="Delete" onClick={() => handleDelete(pdf.file)}>
                    <FaTrash />
                  </Button>
                </td>
              </tr>
            ))}
            {filtered.length === 0 && (
              <tr>
                <td colSpan={4} className="text-center text-muted-foreground py-8">No PDFs found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
